apiVersion: v1
kind: Secret
metadata:
  name: s3-artifacts
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: s3-artifacts
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: mender
    helm.sh/chart: "{{ .Chart.Name }}"
data:
  AWS_URI: {{ .Values.global.s3.AWS_URI | b64enc }}
  AWS_BUCKET: {{ .Values.global.s3.AWS_BUCKET | b64enc }}
  AWS_REGION: {{ .Values.global.s3.AWS_REGION | b64enc }}
{{- if not .Values.global.s3.useServiceAccount }}
  AWS_AUTH_KEY: {{ .Values.global.s3.AWS_ACCESS_KEY_ID | b64enc }}
  AWS_AUTH_SECRET: {{ .Values.global.s3.AWS_SECRET_ACCESS_KEY | b64enc }}
{{- end }}
{{- if not .Values.global.s3.useServiceAccount }}
  # this is required because deprecated func is used https://github.com/mendersoftware/deployments/blob/554b194e1ff389e50200644b8034bb012ede197a/s3/filestorage.go#L114
  AWS_SDK_LOAD_CONFIG: "1"
{{- end }}